application: ima-historic
version: 1
runtime: python
api_version: 1

handlers:
- url: /tasks/.*
  script: home.py
  login: admin

- url: /charts
  static_dir: charts

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: home.py
